version: '3.8'

services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
            - DATABASE_URL=postgresql://app:password@postgres:5432/app_db
        depends_on:
            - postgres

    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: password
            POSTGRES_DB: app_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres_data: